============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.4.0, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /workspaces/dihya.io
configfile: pytest.ini
plugins: anyio-4.9.0, mock-3.14.1, asyncio-1.0.0, cov-6.1.1
asyncio: mode=strict, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_ ERROR collecting backend/components/metiers/threed/tests_centralises/api/accessibility/accessibility.test.py _
ImportError while importing test module '/workspaces/dihya.io/backend/components/metiers/threed/tests_centralises/api/accessibility/accessibility.test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/vscode/.local/lib/python3.10/site-packages/_pytest/python.py:497: in importtestmodule
    mod = import_path(
/home/vscode/.local/lib/python3.10/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:992: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1004: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'threed.tests_centralises.api.accessibility.accessibility'
=========================== short test summary info ============================
ERROR api/accessibility/accessibility.test.py
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.32s ==========================
